# shellcheck shell=sh
# shellcheck disable=SC1091

export HISTCONTROL="ignoreboth"
export HISTFILE="$HOME/.histfile"
export HISTFILESIZE="20000"
export HISTSIZE="10000"
export SAVEHIST="10000"
export DOCKER_BUILDKIT="1"
export NODE_OPTIONS="--max_old_space_size=4096"
export KUBECTL_EXTERNAL_DIFF="diff --color -u -N -I generation"
export CARGO_NET_GIT_FETCH_WITH_CLI="true"
export DOTNET_WATCH_RESTART_ON_RUDE_EDIT="true"
export NPM_CONFIG_YES="true"
export NPM_CONFIG_FUND="false"
export CLR_OPENSSL_VERSION_OVERRIDE="1.1"

export HOMEBREW_PREFIX="/home/linuxbrew/.linuxbrew"
export HOMEBREW_CELLAR="/home/linuxbrew/.linuxbrew/Cellar"
export HOMEBREW_REPOSITORY="/home/linuxbrew/.linuxbrew/Homebrew"
export PATH="/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin${PATH+:$PATH}"
export MANPATH="/home/linuxbrew/.linuxbrew/share/man${MANPATH+:$MANPATH}:"
export INFOPATH="/home/linuxbrew/.linuxbrew/share/info:${INFOPATH:-}"
export BUN_INSTALL="$HOME/.bun"
export DOTNET_ROOT="$HOME/.dotnet"

export PATH="$PATH:$BUN_INSTALL/bin"
export PATH="$PATH:$HOME/go/bin"
export PATH="$PATH:$HOME/.arkade/bin"
export PATH="$PATH:${KREW_ROOT:-$HOME/.krew}/bin"
export PATH="$PATH:$HOME/.cargo/bin"
export PATH="$PATH:$HOME/.dotnet"
export PATH="$PATH:$HOME/.dotnet/tools"
export PATH="$PATH:$HOME/.go/bin"
export PATH="$PATH:$HOME/.local/bin"
export PATH="$PATH:$HOME/bin"
export PATH="$PATH:/snap/bin"
export PATH="$PATH:/usr/local/sbin"
export PATH="$PATH:/usr/sbin"
export PATH="$PATH:/sbin"
