version: '3'
services:
  jenkins:
    image: chneau/jenkinsdid:alpine
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /containers/jenkins/:/var/jenkins_home/
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.role == manager
  artifactory:
    image: lolhens/artifactory
    ports:
      - 8081:8081
    volumes:
      - /containers/artifactory/:/usr/local/appdata/artifactory/
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.role == manager
  netdata:
    image: titpetric/netdata
    ports:
      - 8082:19999
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.role == manager
  portainer:
    image: portainer/portainer
    ports:
      - 888:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /containers/portainer:/data
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.role == manager
